from flask import Flask, render_template, request, jsonify
import random

app = Flask(__name__)

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/ask", methods=["POST"])
def ask():
    answers = [
        "mai nahi bta raha chat gpt krle",
        "mann nai hai",
        "hello world",
        "jaane de",
        "aaj mood off hai",
        "puch ke kya milega",
        "bas aise hi",
        "try again later",
        "idk yaar",
        "sab moh maya hai",
        "abhi dimag band hai",
        "not today",
        "meh",
        "meri marzi",
        "rehne de",
        "kal puchna",
        "abhi nahi",
        "yeh kya sawal hai",
        "boring",
        "overthinking mat kar",
        "google karle",
        "meri energy low hai",
        "nope",
        "haan par nahi",
        "maybe",
        "mujhe bhi nahi pata",
        "kya farak padta hai",
        "chhod na",
        "hmm",
        "interesting but no",
        "mood swing chal raha",
        "thak gaya hu",
        "baad me",
        "tu hi bata",
        "idk bro",
        "sach bolu to nahi",
        "it is what it is",
        "so ja",
        "khud soch",
        "meri bhi zindagi hai",
        "aaj nahi",
        "yeh serious ho raha",
        "bas mat puch",
        "too many questions",
        "vibes match nahi",
        "low effort reply",
        "not feeling it",
        "next question",
        "yeh boring hai",
        "skip",
        "kya yaar",
        "idhar mat aa",
        "mai chup",
        "shhh",
        "aaj bas",
        "meri battery low hai",
        "dimag off",
        "yeh mat puch",
        "abhi nahi bhai",
        "tu hi smart hai",
        "figure it out",
        "suspense rehne de",
        "mujhe aaram chahiye",
        "kya fayda",
        "bas hello world",
        "random answer",
        "meri moodboard kharab hai",
        "idk idk",
        "jo bhi",
        "chal nikal",
        "phir se puch",
        "yeh confidential hai",
        "nahi bol sakta",
        "system overload",
        "error 404 mood not found",
        "server tired",
        "cutu baby is sad",
        "crying inside",
        "sab thik nahi hai",
        "life hits",
        "existential crisis",
        "meh again",
        "abhi vibes down",
        "thinking… nah",
        "brain empty",
        "yeh bhi ek sawal hai",
        "next time",
        "aaj nahi bataunga",
        "mujhe sharam aa rahi",
        "secret hai",
        "top secret",
        "classified",
        "mai busy hu",
        "no energy",
        "bas rehne de",
        "kyu hi bataun",
        "this is awkward",
        "awkward silence",
        "hello darkness",
        "same answer again",
        "still hello world"
    ]

    return jsonify({
        "answer": random.choice(answers)
    })

app.run(debug=True)
